name: ZIZI
on: [push]
jobs:
  ZIZI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build ml_model
      - run: docker tag ml_model ${{secrets.LOGIN_SECRET}}/tp2-mlops
      - run: docker login -u ${{secrets.LOGIN_SECRET}} -p ${{secrets.PAT_SECRET}}
      - run: docker push ${{secrets.LOGIN_SECRET}}/tp2-mlops
      - run: sshpass -p "${{secrets.SSH_PASSWORD}}" ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} -o StrictHostKeyChecking=no << 'EOF'
      - run: docker image pull ${{secrets.LOGIN_SECRET}}/tp2-mlops
      - run: docker run -d -p 6969:6969 ${{secrets.LOGIN_SECRET}}/tp2-mlops:latest
      - run: echo "DONE !"
